# -*- coding: utf-8 -*-
"""Iris Flower Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6m9BXjaK-OLk8VCiRbATJ2x3PAEc69X
"""

import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

iris=load_iris()

"""# **EDA**"""

dir(iris)

iris.data[0]

iris.target_names[0:9]
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target

iris.feature_names
iris.target
# features=['DESCR','feature_names','data','target']
X=df.drop(['target'],axis=1)
Y = df['target']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

print(len(X_train))
len(X_test)

from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(X_train,y_train)

reg.score(X_test,y_test)

y_pred=reg.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm,annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

df = df.drop(['sepal length (cm)','sepal width (cm)'],axis = 'columns')

plt.scatter(df[	'petal length (cm)'],df['petal width (cm)'])

km = KMeans(n_clusters=3)
y_pred = km.fit_predict(df)
y_pred

df['cluster'] = y_pred
df

df1 = df[df.cluster==0]
df2 = df[df.cluster==1]
df3 = df[df.cluster==2]

plt.scatter(df1['petal length (cm)'],df1['petal width (cm)'],color='green')
plt.scatter(df2['petal length (cm)'],df2['petal width (cm)'],color='blue')
plt.scatter(df3['petal length (cm)'],df3['petal width (cm)'],color='red')
# plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='+',label='centroid')
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')
print()
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='+',label='centroid')

plt.legend()

